### ISSUE TITLE
Bug: Join Selected Lines doesn't work like Intellij

### ISSUE THREAD

**Issue by TheBestPessimist** [KrazyManJ/obsidian-keyshots#14]
In intellij, if i select no lines and run the shortcut (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>), then it concatenates current line with the one below, until there are no more lines below. At that point the shortcut does nothing.

In keyshots, i **must** select all my lines before running the action, which is a much slower UX.

**Comment by TheBestPessimist** [comment]
2. In obsidian f i select multiple lines, it joins them like this: `line1line2line3` etc. In intellij it adds a space between the joined lines: `line1 line2 line3`. This should be added too.

**Comment by TheBestPessimist** [comment]
3. If i have multiple selections via multiple cursors, only the first one actually gets merged while the rest are ignored.

**Comment by KrazyManJ** [comment]
Hello @TheBestPessimist, thank you for your issue post.

First I apologize for late response, I was busy finishing semester at Uni.

The logic behind shifting selections is kind of complicated and I did not catch all errors of that, I apologize. Anyways you are correct, both in JetBrains and VSCode `Join Selected Lines` command does that, even VSCode one will join lines even if selection is one line (it keeps this selection as it is).

I will implement fix for this in `2.5.0` with re-work of whole plugin + additional features. It looks like It’s on the right track!

Stay tuned, I will inform you through this issue post. Thank you for making Keyshots a better plugin.

**Comment by KrazyManJ** [comment]
I have released hotfix 2.5.1 for this issue. Please try it out.

https://github.com/KrazyManJ/obsidian-keyshots/releases/tag/2.5.1

**Comment by TheBestPessimist** [comment]
There is no selection. Nice!

However there is still an issue with multi caret joining: except for the first caret, the others aren't joining the lines 'where i put the caret' but below. 
I think this happens because the caret line must be 'moved up with 1' after every join of every caret 'above'. Or even better, moved up by 'the amount of lines joined together after every join of every caret above.

Say I have a file with lines and i put my carets on lines 3, 9 ,15.
```
1
2
3
...
20
```

When I press `join lines` once, i expect the following:
```
1
2
3 4
5
...
8
9 10
11
...
14
15 16
17
...
20
```

When I press `join lines` a second time, i expect the following:
```
1
2
3 4 5
6
...
8
9 10 11
12
...
14
15 16 17
18
...
20
```

Videos will show better what i mean. Obsidian on the left, intellij on the right.

1. Cursors on lines 3, 9, 15:
https://github.com/user-attachments/assets/00f39533-9d58-4193-ab73-aa9c8a72efb9

2. Cursors on lines 3 4, 9 10, 15 16:
https://github.com/user-attachments/assets/d3560894-b87b-47df-9bbf-8d1d3f298828

**Comment by KrazyManJ** [comment]
The first Issue I fixed successfully and will be included in 2.5.2 hotfix, the second one I cannot do anything with that, because I use replaceRange which registers as one action in Obsidian, and each action has it's own undo. This happens only for multiple selections, because each selection = one action.

Only possible way fixing this is to re-program whole thing to replace whole document so it will register as one action.

Now I am solving another issue that when I make selection ending on end of the line, it will select somehow another line as well.

**Comment by KrazyManJ** [comment]
I have released hotfix for this issue. Please check it out (hope everything is okay now :D )

https://github.com/KrazyManJ/obsidian-keyshots/releases/tag/2.5.2

**Comment by TheBestPessimist** [comment]
> 1. Cursors on lines 3, 9, 15

This works OK. Thanks for the fix.

> 2. Cursors on lines 3 4, 9 10, 15 16:

This one is still bugged, but in a different way.

**Comment by KrazyManJ** [comment]
Hello @TheBestPessimist , please look at this video representing how would Join selected lines work with undo. After a bit research I found out there is transaction method that handles undo for multiple actions.

https://github.com/user-attachments/assets/ffada522-bb18-4637-ba64-84de1b96ba51

The union of selections in second case is inspired by VSCode.

Is it what you are looking for?

**Comment by KrazyManJ** [comment]
@TheBestPessimist, I have released now a version 2.6.0 fixing this. Please look at it and tell me if everything is okay.

https://github.com/KrazyManJ/obsidian-keyshots/releases/tag/2.6.0

**Comment by TheBestPessimist** [comment]
This one seems to be working OK in all cases i thought to throw at it. Awesome job @KrazyManJ !
